[package]
name = "meshlaked"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "meshlaked"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
axum.workspace = true
base64.workspace = true
clap.workspace = true
ed25519-dalek.workspace = true
getrandom.workspace = true
ipnet.workspace = true
igd-next.workspace = true
libloading.workspace = true
meshlake-core = { path = "../meshlake-core" }
reqwest.workspace = true
rpassword.workspace = true
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
uuid.workspace = true
webpki.workspace = true
zeroize.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true
